### ISSUE TITLE
Support for russian files possible?

### ISSUE THREAD

**Issue by assassinscrack** [Twigzie/Fantality-LostArkRenamer#2]
Do you think it'd be possible to add support for russian game files?

**Comment by Twigzie** [comment]
> Do you think it'd be possible to add support for russian game files?

Can I get a screenshot of what your game files look like?

**Comment by assassinscrack** [comment]
Sorry, I think I had mixed things up and these are actually NA/EU files.

I got errors trying to decrypt them and thought they must've been russian.
I didn't just take them from the game they were lying in a folder..

Figured out earlier I was using the prompt incorrectly.


May I ask though if you think it'd be possible to rename the contents of a file?

Like, rename the files inside a bnk file so they can be extracted in a readable / usable manner?
That's what I'm trying to do, was thinking this tool could help with that.

**Comment by Twigzie** [comment]
> Like, rename the files inside a bnk file so they can be extracted in a readable / usable manner?\nThat's what I'm trying to do, was thinking this tool could help with that.

Not sure I quite understand what you hope to accomplish. Do you mean just rename the file itself or scan the contents of said file and rename any files it finds within said file?

If so, that's an entirely different process as (from what I know) audio (bnk) files are encrypted and need to be decrypted using a different program.

**Comment by assassinscrack** [comment]
> > Like, rename the files inside a bnk file so they can be extracted in a readable / usable manner?\nThat's what I'm trying to do, was thinking this tool could help with that.
> 
> Not sure I quite understand what you hope to accomplish. Do you mean just rename the file itself or scan the contents of said file and rename any files it finds within said file?
> 
> If so, that's an entirely different process as (from what I know) audio (bnk) files are encrypted and need to be decrypted using a different program.

Yes I wanted to rename the contents of the files.
They are already decrypted as in - I can read, play, extract and convert them but they still have obfuscated names.
Which is an issue with there being 600+ files each..

Here is a preview of a file like this
![exfile](https://github.com/Twigzie/Fantality-LostArkRenamer/assets/84638875/2a8fc486-4410-4db2-ab6a-42d1255771e7)

**Comment by Twigzie** [comment]
Hmm, I'll take a look. Any chance you can tell me which file you're using? Maybe upload it somewhere?

EDIT: I think I know what you have, you just have a folder with a lot of audio files in it. I just pushed a new program that helps with extracting audio. Its not released yet but once I know its in a working state, ill release it.

**Comment by assassinscrack** [comment]
I see, that's great to hear. Appreciate you troubling yourself with this.
Can I assume you no longer need a link/file then? The one in the screenshot was just an example here.
What I have are all voice files taken from WwiseAudio > English(US).

**Comment by Twigzie** [comment]
> WwiseAudio > English(US)

Ok, I figured. Yeah, the program I made uses lautool to decrypt and Wwise unpacked to extract files. I tried a bunch of different files and they all seem to unpack with their proper names. No need to de-obfuscate any names.

Edit: ![Untitled](https://github.com/Twigzie/Fantality-LostArkRenamer/assets/1693796/7034aaaa-c2c8-4371-95fb-0f402f1cab55)

Edit Again...
I just published a pre-release version for you [Here](https://github.com/Twigzie/Fantality-LostArkAudioExtractor/releases/tag/2024.0413.89.1915) if you wanna give it a try. Once you download it, I'll most likely remove the release cause I don't want pre-release versions available. Just figured you could try it out if interested. Oh, and please open any issues over on that repo please.
