### ISSUE TITLE
hadrcoded path?

### ISSUE THREAD

**Issue by Asciicodeplus** [Twigzie/Fantality-LostArkRenamer#3]
the latest version (2024.0413.83.1835) doesn't seem to work, it always crashes no matter the input (file, folder or array), seems it's expecting this to be present:

[Processing]

        > Type: 'List'
        > Source: C:\Users\parad\Desktop\asdasdasd.txt

As it throws this error:

[Error]: System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\parad\Desktop\asdasdasd.txt'.

 version 2024.0411.80.2104 works fine with the same parameters for all 3 (file, folder and array)

**Comment by Twigzie** [comment]
Yes, my apologies. Guess i got carried away with the Audio tool that I forgot I was debugging the Renamer XD

The new version is available [here](https://github.com/Twigzie/Fantality-LostArkRenamer/releases/tag/2024.0415.84.0147)

**Comment by Twigzie** [comment]
Let me know if it works and I'll close the issue. Thanks!

**Comment by Asciicodeplus** [comment]
yup, the new one works, thx a lot
