### ISSUE TITLE
Names with suffixes don't get deobfuscated correctly

### ISSUE THREAD

**Issue by Poyoanon** [Twigzie/Fantality-LostArkRenamer#4]
Certain .ipk files have certain suffixes such as .English, .French, .Spanish and .German. 

For example, in EFGame/Movies, there is SZSTEN387HFT6NV7W0VENTO7XZVLS.English.ipk, which doesn't deobfuscate correctly, but when removing the suffix from the name it correctly outputs as TUTORIAL_MOVIE_PERIODQUEST.
![image](https://github.com/Twigzie/Fantality-LostArkRenamer/assets/27013504/db476d20-6074-47c4-9c21-a94ffff82e45)
![image](https://github.com/Twigzie/Fantality-LostArkRenamer/assets/27013504/a3dc81ca-f9b7-4c11-9751-1e3a6207f329)

**Comment by Twigzie** [comment]
Thanks, I didn't research what types of filenames are used. I've been lacking in my updates, I'll do my best to get an update out soon. I plan on abandoning this program when I get my file explorer running anyways, updates might reflect when that is released.

**Comment by Twigzie** [comment]
Issue has been fixed in the new program, see below

![Screenshot 2024-07-06 182613](https://github.com/Twigzie/Fantality-LostArkRenamer/assets/1693796/1847a57b-00b4-42f8-89cf-7551365b87c3)

**Comment by Poyoanon** [comment]
Thanks, the file explorer looks good as well. :)
