### ISSUE TITLE
LostArkRenamer appears to work but nothing changes?

### ISSUE THREAD

**Issue by sorrytobotheryou** [Twigzie/Fantality-LostArkRenamer#5]
Hello! 

I'm reaching out to you on behalf of a friend who is a modder trying to use LostArkRenamer to rename the .upk files so they can easily find what they're looking for. As far as we can tell, the program is working correctly. No errors appear, and it reports as if it was completed successfully, but the .upk file remains unchanged. Nothing new appears in the location. 
![image](https://github.com/user-attachments/assets/3f04ecbb-6f42-4c1a-a00d-e193546d2345)

We've tried moving the files to another location and even tested them on another PC.
We've ensured the files are not read-only, run the renamer as admin, and tested the list function incorrectly to check the error handling. The program was able to report the error and output a log file just fine. 

So, at this point, we're not sure why it isn't working.

Do you have any thoughts on what might be going on? Feel free to let me know if you need more information.

Thanks!

**Comment by Twigzie** [comment]
This app does not rename the actual files.

________________________________
From: sorrytobotheryou ***@***.***>
Sent: July 22, 2024 10:22 AM
To: Twigzie/Fantality-LostArkRenamer ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Twigzie/Fantality-LostArkRenamer] LostArkRenamer appears to work but nothing changes? (Issue #5)


Hello!

I'm reaching out to you on behalf of a friend who is a modder trying to use LostArkRenamer to rename the .upk files so they can easily find what they're looking for. As far as we can tell, the program is working correctly. No errors appear, and it reports as if it was completed successfully, but the .upk file remains unchanged. Nothing new appears in the location.
image.png (view on web)<https://github.com/user-attachments/assets/3f04ecbb-6f42-4c1a-a00d-e193546d2345>

We've tried moving the files to another location and even tested them on another PC.
We've ensured the files are not read-only, run the renamer as admin, and tested the list function incorrectly to check the error handling. The program was able to report the error and output a log file just fine.

So, at this point, we're not sure why it isn't working, and I suggested reaching out to you, but their anxiety got the best of them. So here we are :)

Do you have any thoughts on what might be going on? Feel free to let me know if you need more information.

Thanks!

**Comment by sorrytobotheryou** [comment]
Ah, sorry for the misunderstanding. Thank you for taking the time to respond.

**Comment by Twigzie** [comment]
> Ah, sorry for the misunderstanding. Thank you for taking the time to respond.

Just an update, I uploaded a new version that will rename the files.

**Comment by sorrytobotheryou** [comment]
Legend, thank you for the update!
